/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Thu Oct 13 14:02:10 2016. */

#ifndef PB_MEASUREMENT_PB_H_INCLUDED
#define PB_MEASUREMENT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _api_Measurement {
    bool motion;
    uint32_t water;
/* @@protoc_insertion_point(struct:api_Measurement) */
} api_Measurement;

/* Default values for struct fields */

/* Initializer values for message structs */
#define api_Measurement_init_default             {0, 0}
#define api_Measurement_init_zero                {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define api_Measurement_motion_tag               1
#define api_Measurement_water_tag                2

/* Struct field encoding specification for nanopb */
extern const pb_field_t api_Measurement_fields[3];

/* Maximum encoded size of messages (where known) */
#define api_Measurement_size                     8

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MEASUREMENT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
